words = [
    "amigo", "barco", "cama", "dente", "elefante", "faca", "gato", "homem", "igreja", "janela",
    "kiwi", "livro", "maca", "navio", "ovo", "pato", "quadro", "rua", "sapato", "tigre",
    "urso", "vaca", "whisky", "xarope", "yeti", "zebra", "bola", "copo", "dado", "espelho",
    "fogo", "garfo", "hotel", "ilha", "jogo", "lobo", "mala", "noite", "oculo", "porta",
    "quente", "roda", "sal", "trem", "uva", "vela", "wolframio", "xadrez", "yoga", "zangado",
    "abelha", "banana", "cavalo", "dedo", "enfermeiro", "ferro", "grama", "harpa", "idade", "joia",
    "luz", "mapa", "nuvem", "olho", "pente", "quilo", "rato", "sino", "teto", "unha",
    "vulto", "watt", "xaxim", "yeti", "zoologico", "alface", "banco", "canoa", "doce", "estrela",
    "foca", "gelo", "hiena", "idoso", "jornal", "limonada", "milho", "noz", "oculos", "pijama",
    "quiosque", "rede", "sombra", "tampa", "urso", "vinho", "wolverine", "xampu", "yamaha", "zangao","anjo", "blusa", "cinto", "dama", "escada", "fundo", "gira", "hobby", "iguana", "jabuti",
    "lenco", "moeda", "nicho", "orvalho", "prato", "queda", "rosto", "sonho", "tapete", "urso",
    "vulto", "whey", "xaxim", "yeti", "zorra", "areia", "baile", "cobra", "dado", "eco",
    "festa", "gole", "horta", "ilha", "jovem", "lousa", "mente", "norte", "onda", "pote",
    "quimico", "resma", "sala", "tinta", "urna", "vidro", "wok", "xale", "yeti", "zelo",
    "altura", "bebida", "capim", "dente", "elogio", "farda", "gancho", "heroi", "idade", "jogo",
    "lona", "moita", "ninho", "oceano", "poco", "quilo", "rede", "sapato", "trapo", "urso",
    "vento", "watt", "xadrez", "yeti", "zebra", "alegria", "bicho", "cravo", "dedo", "espora",
    "fita", "galho", "haste", "idoso", "janela", "limo", "mundo", "ninho", "ovo", "pano",
    "quadro", "rua", "sol", "tempo", "urna", "vida", "watt", "xaxim", "yeti", "zorro",
    "agua", "bola", "casaco", "doce", "espora", "folha", "garrafa", "horta", "icone", "jarra",
    "lobo", "mala", "nuvem", "olho", "pente", "quadro", "rosa", "saia", "telha", "urso",
    "vaso", "watt", "xaxim", "yeti", "zangado", "alvo", "barco", "copo", "dado", "estojo",
    "flauta", "guitarra", "helice", "ilha", "jornal", "lata", "mel", "navio", "orvalho", "prego",
    "quebra", "rede", "sol", "trilha", "urna", "vento", "wok", "xadrez", "yamaha", "zelo",
    "anel", "brisa", "caminho", "dia", "elefante", "foco", "gado", "historia", "icone", "janela",
    "lente", "mato", "noite", "onda", "pico", "quarto", "ruido", "som", "teto", "uniao"
]